---
title: "vault"
author: "Ben Gonzalez"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
  html_document:
vignette: >
  %\VignetteIndexEntry{vault}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}  
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

### Installation

```{r setup,eval=FALSE}
devtools::install_git(url = "https://github.com/gonzalezben81/vault.git")
library(vault)
```

#### Post/Write secrets to vault

```{r eval=FALSE}
vault::post_vault_data(url = "vault-url.com",path = "secret-path",token = token,secrets = list(one="two",three="four"))
```

#### Get/Retrieve secrets from vault

```{r eval=FALSE}
get_vault_data(url = "vault-url.com",path = "secret-path",token = token)
```

#### Wrap secrets via vault

This function allows you to wrap secrets from vault and send them securly to another person via plain text. The vault token returned is only good for one time use, 

```{r eval=FALSE}
wrap_secrets(url = "vault-url.com",token = token ,secrets_to_wrap = c("one"=one,"two"=two),ttl = "30m")
```